footprint: [[0.235, 0.180], [0.235, -0.180], [-0.235, -0.180], [-0.235, 0.180]]
footprint_padding: 0.03
transform_tolerance: 1.0

obstacle_layer:
  enabled: true
  observation_sources: scan
  obstacle_range: 3.0
  raytrace_range: 4.0
  track_unknown_space: true
  combination_method: 1
  scan:
    sensor_frame: laser_link
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true
    inf_is_valid: true
    expected_update_rate: 0.0

inflation_layer:
  enabled: true
  cost_scaling_factor: 6.0
  inflation_radius: 0.40

static_layer:
  enabled: true
  map_topic: /map
